export const api = {
  baseURL: "https://qut-association.iran.liara.run",
  login: "/account/login/",
  register: "/account/register/",
  forgotPass: "/account/forgot_password/",
  changePass: "/account/change_password/",
  tokenValidation: "/account/token_validation/",
  userProfile: "/account/user/profile/",
  updateUserProfile: "/account/user/update/",
  podcasts: "/post/podcast/archive/",
  events: "/post/event/archive/",
  eventRegister: "/post/event/attend/",
  comments: "/post/comment/list/",
  addComment: "/post/comment/send/",
  userEvents: "/account/user/events/",
  eventCanceling: "/post/event/canceling/",
  singleEvent: "/post/event/",
  singleBlog: "/post/article/",
  userSingleBlog: (slug: string) => `/post/article/${slug}/edit/`,
  blogs: "/post/article/",
  vidoes: "/course/v2/all_course_video/",
  blogCategories: "/post/categories/",
  videosCategories: "/course/v2/courses_category/",
  blogsByCategory: (slug: string) => `/post/${slug}/articles/`,
  videosByCategory: (slug: string) => `/course/v2/${slug}/courses_video/`,
  uploader: "/post/image/upload/",
  createBlog: "/post/article/",
  updateBlog: "/post/article/",
  userBlogs: "/account/articles/",
  homeBlogs: "/home/list_article_view/",
  homePodcast: "/home/list_podcast_view/",
  journal: "/post/journal/archive/",
};
